/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { OrderItemDto } from './orderItemDto';

export interface CreateOrderDto {
  /** Họ và tên đệm */
  lastName: string;
  /** Tên */
  firstName: string;
  /** Email */
  email?: string;
  /** Số điện thoại */
  phoneNumber: string;
  /** Danh sách sản phẩm và vận động viên */
  items: OrderItemDto[];
}
