/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { InitPaymentDtoPaymentMethod } from './initPaymentDtoPaymentMethod';

export interface InitPaymentDto {
  paymentMethod: InitPaymentDtoPaymentMethod;
  returnUrl?: string;
}
