/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  InitSepayPaymentDto,
  SepayIpnPayloadDto
} from '../../schemas';

import { defaultMutator } from '../../api/axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Initialize SePay payment for a campaign order
 */
export type campaignOrderSepayControllerInitPaymentResponse200 = {
  data: void
  status: 200
}

export type campaignOrderSepayControllerInitPaymentResponseSuccess = (campaignOrderSepayControllerInitPaymentResponse200) & {
  headers: Headers;
};
;

export type campaignOrderSepayControllerInitPaymentResponse = (campaignOrderSepayControllerInitPaymentResponseSuccess)

export const getCampaignOrderSepayControllerInitPaymentUrl = (campaignId: string,
    orderCode: string,) => {


  

  return `/campaigns/${campaignId}/orders/${orderCode}/sepay/init`
}

export const campaignOrderSepayControllerInitPayment = async (campaignId: string,
    orderCode: string,
    initSepayPaymentDto: InitSepayPaymentDto, options?: RequestInit): Promise<campaignOrderSepayControllerInitPaymentResponse> => {
  
  return defaultMutator<campaignOrderSepayControllerInitPaymentResponse>(getCampaignOrderSepayControllerInitPaymentUrl(campaignId,orderCode),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      initSepayPaymentDto,)
  }
);}
  



export const getCampaignOrderSepayControllerInitPaymentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext> => {

const mutationKey = ['campaignOrderSepayControllerInitPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, {campaignId: string;orderCode: string;data: InitSepayPaymentDto}> = (props) => {
          const {campaignId,orderCode,data} = props ?? {};

          return  campaignOrderSepayControllerInitPayment(campaignId,orderCode,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderSepayControllerInitPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>>
    export type CampaignOrderSepayControllerInitPaymentMutationBody = InitSepayPaymentDto
    export type CampaignOrderSepayControllerInitPaymentMutationError = unknown

    /**
 * @summary Initialize SePay payment for a campaign order
 */
export const useCampaignOrderSepayControllerInitPayment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>, TError,{campaignId: string;orderCode: string;data: InitSepayPaymentDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderSepayControllerInitPayment>>,
        TError,
        {campaignId: string;orderCode: string;data: InitSepayPaymentDto},
        TContext
      > => {
      return useMutation(getCampaignOrderSepayControllerInitPaymentMutationOptions(options), queryClient);
    }
    /**
 * @summary SePay IPN webhook — receives payment confirmation from SePay
 */
export type campaignOrderSepayControllerProcessIpnResponse200 = {
  data: void
  status: 200
}

export type campaignOrderSepayControllerProcessIpnResponseSuccess = (campaignOrderSepayControllerProcessIpnResponse200) & {
  headers: Headers;
};
;

export type campaignOrderSepayControllerProcessIpnResponse = (campaignOrderSepayControllerProcessIpnResponseSuccess)

export const getCampaignOrderSepayControllerProcessIpnUrl = () => {


  

  return `/campaigns/orders/sepay/ipn`
}

export const campaignOrderSepayControllerProcessIpn = async (sepayIpnPayloadDto: SepayIpnPayloadDto, options?: RequestInit): Promise<campaignOrderSepayControllerProcessIpnResponse> => {
  
  return defaultMutator<campaignOrderSepayControllerProcessIpnResponse>(getCampaignOrderSepayControllerProcessIpnUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sepayIpnPayloadDto,)
  }
);}
  



export const getCampaignOrderSepayControllerProcessIpnMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext> => {

const mutationKey = ['campaignOrderSepayControllerProcessIpn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, {data: SepayIpnPayloadDto}> = (props) => {
          const {data} = props ?? {};

          return  campaignOrderSepayControllerProcessIpn(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignOrderSepayControllerProcessIpnMutationResult = NonNullable<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>>
    export type CampaignOrderSepayControllerProcessIpnMutationBody = SepayIpnPayloadDto
    export type CampaignOrderSepayControllerProcessIpnMutationError = unknown

    /**
 * @summary SePay IPN webhook — receives payment confirmation from SePay
 */
export const useCampaignOrderSepayControllerProcessIpn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>, TError,{data: SepayIpnPayloadDto}, TContext>, request?: SecondParameter<typeof defaultMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignOrderSepayControllerProcessIpn>>,
        TError,
        {data: SepayIpnPayloadDto},
        TContext
      > => {
      return useMutation(getCampaignOrderSepayControllerProcessIpnMutationOptions(options), queryClient);
    }
    